### ISSUE TITLE
update pug to 3.0.2

### ISSUE THREAD

**Issue by jerryc127** [hexojs/hexo-renderer-pug#8]
hope update pug to 3.0.2

**Comment by stevenjoezhang** [comment]
Updated in https://github.com/hexojs/hexo-renderer-pug/commit/e91059d39b512a3203554a75c59d2d74a0023807
Need to release a new version on npm @curbengh @yoshinorin

**Comment by jerryc127** [comment]
it have a plan to release a new verson ?

**Comment by yoshinorin** [comment]
@jerryc127 @stevenjoezhang 
Sorry, so the late reply.
I submitted PR #9 for release new version.

**Comment by yoshinorin** [comment]
@jerryc127 
Sorry so late reply.
We just released `2.0.0`

> https://www.npmjs.com/package/hexo-renderer-pug/v/2.0.0
